name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update test-suite sub-module
        run: git submodule update --init --recursive
      - name: install oracle openjdk
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: '23'
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*pom.yaml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: mvn verify
        run: mvn -V --no-transfer-progress --batch-mode clean verify
