name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update test-suite sub-module
        run: git submodule update --init --recursive
      - uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: '25'
          cache: maven
          cache-dependency-path: '**/pom.yaml'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: mvn verify
        run: mvn -V --no-transfer-progress --batch-mode clean verify
