name: release
on:
  workflow_dispatch:
    inputs:
      release_ver:
        description: 'Version to release'
        required: true
      next_ver:
        description: 'Version for next development iteration'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update test-suite sub-module
        run: git submodule update --init --recursive
      - uses: actions/setup-java@v5
        with:
          distribution: oracle
          java-version: '25'
          cache: maven
          cache-dependency-path: '**/pom.yaml'
      - uses: mikefarah/yq@v4

      - name: config git # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
        # https://github.com/actions/checkout/tree/v4.1.7?tab=readme-ov-file#push-a-commit-using-the-built-in-token
        # alt: https://github.com/orgs/community/discussions/40405#discussioncomment-8361451
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: set release version
        run: |
          src/build/yq-assign.sh .version ${{ github.event.inputs.release_ver }} src/build/pom.yaml
          src/build/yq-assign.sh .scm.tag ${{ github.event.inputs.release_ver }} src/build/pom.yaml
          src/build/yq-assign.sh .parent.version ${{ github.event.inputs.release_ver }} jvm/pom.yaml
          src/build/yq-assign.sh .parent.version ${{ github.event.inputs.release_ver }} js/pom.yaml

      - name: commit release
        run: |
          git add src/build/pom.yaml jvm/pom.yaml js/pom.yaml
          git commit -m "[ci skip] prepare release ${{ github.event.inputs.release_ver }}"

      - name: tag release
        run: git tag ${{ github.event.inputs.release_ver }} -m "[ci] release ${{ github.event.inputs.release_ver }}"

      # see: https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c
      - name: install gpg key
        run: |
          cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: mvn deploy
        run: mvn -V --no-transfer-progress --batch-mode --settings .mvn/settings.xml -Dmaven.install.skip=true -P release deploy
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: push release commit and tag
        run: |
          git push origin HEAD
          git push origin ${{ github.event.inputs.release_ver }}

      - name: create gh release
        run: gh release create ${{ github.event.inputs.release_ver }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: set next dev version
        run: |
          src/build/yq-assign.sh .version ${{ github.event.inputs.next_ver }} src/build/pom.yaml
          src/build/yq-assign.sh .scm.tag HEAD src/build/pom.yaml
          src/build/yq-assign.sh .parent.version ${{ github.event.inputs.next_ver }} jvm/pom.yaml
          src/build/yq-assign.sh .parent.version ${{ github.event.inputs.next_ver }} js/pom.yaml

      - name: commit and push next dev version
        run: |
          git add src/build/pom.yaml jvm/pom.yaml js/pom.yaml
          git commit -m "[ci skip] prepare for next development iteration"
          git push
